[project]
name = "transformer-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.2.0",
    "tensorboard>=2.18.0",
    "tokenizers>=0.21.0",
    "torch>=2.5.1",
    "tqdm>=4.67.1",
]
